name: Terraform EC2


on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply      
      run: terraform apply -auto-approve -var="aws_access_key=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ env.AWS_SECRET_ACCESS_KEY }}" -state=output.tfstate

    - name: Save Host Address
      run: terraform output -raw ip_address
        

    - name: Install Packages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.IP_ADDRESS}}
        username: ec2-user
        key: ${{ secrets.PEM_EC2_PAGOS }}
        script: |
            sudo yum install -y nodejs npm git
        
    - name: Create Working Directory
      uses: appleboy/ssh-action@master
      with:
          host: ${{ env.IP_ADDRESS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
              if [ -d "/opt/WorkingDirectoryPagos" ]; then
              sudo rm -rf /opt/WorkingDirectoryPagos
              fi
              sudo mkdir /opt/WorkingDirectoryPagos
              cd /opt/WorkingDirectoryPagos
      
    - name: Clone Repository T2-Devops
      uses: appleboy/ssh-action@master
      with:
          host: ${{ env.IP_ADDRESS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
            sudo git clone https://${{ secrets.PAT}}@github.com/FedeMerayo/DevOps-T2.git /opt/WorkingDirectoryPagos

    - name: Install NPM Packages
      uses: appleboy/ssh-action@master
      with:
          host: ${{ env.IP_ADDRESS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
              sudo npm install express
              sudo npm install -g pm2
      
    - name: Start Node Service
      uses: appleboy/ssh-action@master
      with:
          host: ${{ env.IP_ADDRESS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
            if ! pm2 list | grep -q 'app'; then
            pm2 start -f /opt/WorkingDirectoryPagos/app.js
            fi
         
    - name: Check Status
      uses: appleboy/ssh-action@master
      with:
          host: ${{ env.IP_ADDRESS }}
          username: ec2-user
          key: ${{ secrets.PEM_EC2_PAGOS }}
          script: |
            if pm2 list | grep -q 'app'; then
            echo "La aplicaci칩n est치 corriendo."
            else
            echo "La aplicaci칩n no est치 corriendo."
            fi
      
